//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G6_Website_BQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANHSANPHAM
    {
        public int MASP { get; set; }
        public string TENANH { get; set; }
        public string ANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
