//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G6_Website_BQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA
    {
        public int MAGG { get; set; }
        public string TENMGG { get; set; }
        public Nullable<int> MUCGIAM { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public int MALOAISP { get; set; }
        public Nullable<int> MASK { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
        public virtual SUKIEN SUKIEN { get; set; }
    }
}
