//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G6_Website_BQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.ANHSANPHAMs = new HashSet<ANHSANPHAM>();
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.CHITIETSPs = new HashSet<CHITIETSP>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> MALOAISP { get; set; }
        public Nullable<int> MADM { get; set; }
        public Nullable<int> MATH { get; set; }
        public Nullable<int> MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHSANPHAM> ANHSANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSP> CHITIETSPs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
